# General properties shared by all profiles
continuum-gateway:
  disableIam: true

continuum:
  debug: true
  maxNumberOfCoresToUse: 4

logging:
  level:
    org:
      kinotic: TRACE
    io:
      vertx: DEBUG
